In [1]:
import numpy as np

In [5]:
np.sqrt(455)

21.330729007701542

In [6]:
np.log(np.exp(5.2))

5.2

In [7]:
np.cos(np.pi)

-1.0

In [10]:
vec = np.array([1, 2, 3])
vec

array([1, 2, 3])

In [14]:
mat = np.array([[1,2,3],
               [5,6,7],
               [7,8,9]])
mat

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [15]:
np.matmul(mat, vec)

array([14, 38, 50])

In [18]:
mat.T

array([[1, 5, 7],
       [2, 6, 8],
       [3, 7, 9]])

In [26]:
vec2 = np.arange(0, 15)
vec2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
vec3 = np.arange(0, 15, 3)
vec3

array([ 0,  3,  6,  9, 12])

In [31]:
vec4 = np.linspace(0,5,10)
vec4

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
vec4.reshape([5,2])

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])

In [37]:
vec5 = np.arange(1,6)
vec5

array([1, 2, 3, 4, 5])

In [41]:
vec6 = np.arange(3,8)
vec6

array([3, 4, 5, 6, 7])

In [42]:
vec5 + vec6

array([ 4,  6,  8, 10, 12])

In [43]:
vec6 - vec6

array([0, 0, 0, 0, 0])

In [45]:
vec5 * vec6

array([ 3,  8, 15, 24, 35])

In [46]:
vec5 / vec6

array([0.33333333, 0.5       , 0.6       , 0.66666667, 0.71428571])

In [49]:
rand_mat = np.random.randn(5, 5)
rand_mat

array([[ 0.43211757,  0.14414343, -0.23846039,  0.05381734,  1.2742755 ],
       [-0.46263331, -1.34904612,  0.00508993,  0.87886933, -1.49268265],
       [-0.07159164, -0.30901248,  0.49673025,  2.03260789,  1.87412395],
       [ 0.06123763,  0.24825708,  1.12137891,  1.23540911,  1.08667415],
       [-0.91044543,  1.32818159,  1.38114257, -0.84547784, -1.29862214]])

In [50]:
np.mean(rand_mat)

0.2670433686631888

In [52]:
np.std(rand_mat) #standard deviation

0.9811355399567729

In [53]:
np.min(rand_mat)

-1.4926826531857171

In [54]:
np.max(rand_mat)

2.032607888238454

In [56]:
import numpy as np
import pandas as pd

In [61]:
my_list = [5.5, 6.2, 1.7, 99.8]
myarray = np.array(my_list)
my_list

[5.5, 6.2, 1.7, 99.8]

In [64]:
myseries1 = pd.Series(data = myarray)
myseries1

0     5.5
1     6.2
2     1.7
3    99.8
dtype: float64

In [65]:
mylabels = ['first', 'second', 'thrid', 'fourth']

In [68]:
myseries2 = pd.Series(data = myarray, index = mylabels)
myseries2

first      5.5
second     6.2
thrid      1.7
fourth    99.8
dtype: float64

In [71]:
data = np.random.randn(5,5)
data

array([[-1.75084315,  2.1488781 , -0.26620462,  0.16229795, -1.66184697],
       [-1.05163291, -0.35002894, -0.6168232 ,  2.30233647,  0.12593678],
       [ 0.82460471,  0.26964996,  0.10781787,  1.11768824, -0.18182193],
       [ 0.07614677, -0.68130111, -0.00254663,  0.15236597, -1.32899778],
       [-1.15251691, -0.9056313 ,  1.24453647,  0.26141839,  1.15997755]])

In [74]:
df = pd.DataFrame(data)
df

0         1         2         3         4
0 -1.750843  2.148878 -0.266205  0.162298 -1.661847
1 -1.051633 -0.350029 -0.616823  2.302336  0.125937
2  0.824605  0.269650  0.107818  1.117688 -0.181822
3  0.076147 -0.681301 -0.002547  0.152366 -1.328998
4 -1.152517 -0.905631  1.244536  0.261418  1.159978

In [75]:
df1 = pd.DataFrame(data, index = ['first_row', 'second_row','third_row','fourth_row','fifth_row'],
                  columns = ['first_col', 'second_col', 'third_col', 'fourth_col','fifth_col'])
df1

first_col  second_col  third_col  fourth_col  fifth_col
first_row   -1.750843    2.148878  -0.266205    0.162298  -1.661847
second_row  -1.051633   -0.350029  -0.616823    2.302336   0.125937
third_row    0.824605    0.269650   0.107818    1.117688  -0.181822
fourth_row   0.076147   -0.681301  -0.002547    0.152366  -1.328998
fifth_row   -1.152517   -0.905631   1.244536    0.261418   1.159978

In [82]:
df1[['second_col', 'fourth_col']]

second_col  fourth_col
first_row     2.148878    0.162298
second_row   -0.350029    2.302336
third_row     0.269650    1.117688
fourth_row   -0.681301    0.152366
fifth_row    -0.905631    0.261418

In [87]:
df1.loc[['third_row'],['second_col']]

second_col
third_row     0.26965

In [89]:
df1.loc['second_row']

first_col    -1.051633
second_col   -0.350029
third_col    -0.616823
fourth_col    2.302336
fifth_col     0.125937
Name: second_row, dtype: float64

In [90]:
df1.iloc[1]

first_col    -1.051633
second_col   -0.350029
third_col    -0.616823
fourth_col    2.302336
fifth_col     0.125937
Name: second_row, dtype: float64

In [91]:
df1[df>0]

first_col  second_col  third_col  fourth_col  fifth_col
first_row         NaN         NaN        NaN         NaN        NaN
second_row        NaN         NaN        NaN         NaN        NaN
third_row         NaN         NaN        NaN         NaN        NaN
fourth_row        NaN         NaN        NaN         NaN        NaN
fifth_row         NaN         NaN        NaN         NaN        NaN

In [96]:
df1['sixth_col'] = np.random.randn(5,1)

In [97]:
df1

first_col  second_col  third_col  fourth_col  fifth_col  sixth_col
first_row   -1.750843    2.148878  -0.266205    0.162298  -1.661847  -0.251763
second_row  -1.051633   -0.350029  -0.616823    2.302336   0.125937   0.587723
third_row    0.824605    0.269650   0.107818    1.117688  -0.181822   1.410719
fourth_row   0.076147   -0.681301  -0.002547    0.152366  -1.328998   2.037339
fifth_row   -1.152517   -0.905631   1.244536    0.261418   1.159978   0.549386

In [100]:
df1.drop('third_col', axis = 1, inplace = True)

In [101]:
df1

first_col  second_col  fourth_col  fifth_col  sixth_col
first_row   -1.750843    2.148878    0.162298  -1.661847  -0.251763
second_row  -1.051633   -0.350029    2.302336   0.125937   0.587723
third_row    0.824605    0.269650    1.117688  -0.181822   1.410719
fourth_row   0.076147   -0.681301    0.152366  -1.328998   2.037339
fifth_row   -1.152517   -0.905631    0.261418   1.159978   0.549386

In [103]:
df1.drop('second_row', axis=0)

first_col  second_col  fourth_col  fifth_col  sixth_col
first_row   -1.750843    2.148878    0.162298  -1.661847  -0.251763
third_row    0.824605    0.269650    1.117688  -0.181822   1.410719
fourth_row   0.076147   -0.681301    0.152366  -1.328998   2.037339
fifth_row   -1.152517   -0.905631    0.261418   1.159978   0.549386

In [104]:
df1.reset_index (inplace=True)

In [105]:
df1

index  first_col  second_col  fourth_col  fifth_col  sixth_col
0   first_row  -1.750843    2.148878    0.162298  -1.661847  -0.251763
1  second_row  -1.051633   -0.350029    2.302336   0.125937   0.587723
2   third_row   0.824605    0.269650    1.117688  -0.181822   1.410719
3  fourth_row   0.076147   -0.681301    0.152366  -1.328998   2.037339
4   fifth_row  -1.152517   -0.905631    0.261418   1.159978   0.549386

In [106]:
df1['new_index'] = ['This', 'is', 'the', 'new', 'index']

In [107]:
df1

index  first_col  second_col  fourth_col  fifth_col  sixth_col  \
0   first_row  -1.750843    2.148878    0.162298  -1.661847  -0.251763   
1  second_row  -1.051633   -0.350029    2.302336   0.125937   0.587723   
2   third_row   0.824605    0.269650    1.117688  -0.181822   1.410719   
3  fourth_row   0.076147   -0.681301    0.152366  -1.328998   2.037339   
4   fifth_row  -1.152517   -0.905631    0.261418   1.159978   0.549386   

  new_index  
0      This  
1        is  
2       the  
3       new  
4     index

In [112]:
df1.set_index('new_index', inplace  = True)

In [113]:
df1

index  first_col  second_col  fourth_col  fifth_col  sixth_col
new_index                                                                     
This        first_row  -1.750843    2.148878    0.162298  -1.661847  -0.251763
is         second_row  -1.051633   -0.350029    2.302336   0.125937   0.587723
the         third_row   0.824605    0.269650    1.117688  -0.181822   1.410719
new        fourth_row   0.076147   -0.681301    0.152366  -1.328998   2.037339
index       fifth_row  -1.152517   -0.905631    0.261418   1.159978   0.549386

In [115]:
#Joins

In [ ]:
#left join
#Right join
#Inner join
#Outer Join

In [116]:
df4 = pd.DataFrame({"Q1" : [101,102,103],
              'Q2' : [201, 202, 203]},
              index = ['I0','I1','I2']
    
)
df4

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [117]:
df5 = pd.DataFrame({"Q3" : [301,302,303],
              'Q4' : [401, 402, 403]},
              index = ['I0','I2','I3']
    
)
df5

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

In [118]:
df4.join(df5, how = 'right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

In [119]:
df4.join(df5, how = 'left')

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I2  103  203  302.0  402.0

In [120]:
df4.join(df5, how = 'outer')

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [121]:
df4.join(df5, how = 'inner')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I2  103  203  302  402